### ISSUE TITLE
Trying to install via nuget into .Net Framework 4.5.1 fails

### ISSUE THREAD

**Issue by jeggs** [SymphonyPlatformSolutions/symphony-api-client-dotnet#9]
Hi, I am trying to install the package via the nuget console, unfortunately I get the following error message
Install-Package : Could not install package 'symphony-apiclient-dotnet 1.0.16'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5.1', but the package does not contain any assembly references or content files that are compatible with 
that framework. For more information, contact the package author.

Which .Net Framework version should I use?
thanks
Jörg

**Comment by mistryvinay** [comment]
Hi Jörg,
The supported .Net Framework version for this client is .Net Core 2.0+

I hope that helps.
Thanks,
Vinay

**Comment by jeggs** [comment]
Thanks. Will there be a version supporting lower Framework versions?
Regards
Jörg

**Comment by mistryvinay** [comment]
Hi Jörg,
There are no plans to support the older frameworks unfortunately.
Regards,
Vinay

**Comment by jeggs** [comment]
Ok thanks a lot.
